// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxjqbzuzeagwcjwqmhzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4anFienV6ZWFnd2Nqd3FtaHpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDAwMTQsImV4cCI6MjA3MjgxNjAxNH0.qmsMFLQNQUN998baMxv1extf2WjHZarcy6eTXQzujIg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});